name: "Camera Volume"
description: "Extract audio volume levels from camera mics via RTSP streams using FFmpeg"
version: "1.0.3"
slug: "camera-volume"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options: {}
schema: {}
logo: "logo.png"
icon: "icon.png"
map:
  - config:rw
